walkgen_params:
  params:
    N_phase_return: 2 # Number of step to return (N_phase_return surfaces for each foot)

  gait:
    type: "trot" # Only "walk" or "trot" working
    dt: 0.01
    horizon: 125 # Horizon length of the queue of contact.
    nsteps: 1 # Number of iteration.
    stepHeight: 0.15 # Step height [m]
    trot:
      N_ds: 80
      N_ss: 35
      N_uds: 0
      N_uss: 0
    walk:
      N_ds: 90
      N_ss: 70
      N_uds: 0
      N_uss: 0
    feet_names: ["FL_foot","RL_foot","FR_foot","RR_foot"]
    feet_names_sl1m:  [FL_foot, FR_foot, RL_foot, RR_foot]
    shoulder_offsets: [[0.367, 0.2],[0.367, -0.2],[-0.367, 0.2],[-0.367, -0.2]] 
  bezier:
    margin_up: 0.08  # Margin [m] wrt to the segment crossed in the surface.
    t_margin_up: 0.045  # % of the curve constrained around critical point.
    z_margin_up: 0.045  # % of the curve after the critical point.
    margin_down: 0.08  # Margin [m] wrt to the segment crossed in the surface.
    t_margin_down: 0.045  # % of the curve constrained around critical point.
    z_margin_down: 0.045  # % of the curve after the critical point.
    N_sample: 10  # Number of sample in the least square optimisation for Bezier coeffs
    N_sample_ineq: 8  # Number of sample while browsing the curve
    degree: 7  # Degree of the Bezier curve
    early_termination_ratio: 0.7 # % of the flying to at which stop the end-position and curve optimisation(avoid slips at the end)
