walkgen_params:
  params:
    N_phase_return: 3 # Number of step to return (N_phase_return surfaces for each foot)
    com: False # Optimisation of the CoM
    horizon: 8 # Number of fstep opitimised.

  heightmap:
    fitsize_x: 10
    fitsize_y: 5
    fitlength: 0.3 # half-square size centered around position of the robot.
    recompute_slope: False # Recompute the slope of the terrain for each contact phase configuration.